### ISSUE TITLE
Tracking issue for packaging all known handlers

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#533]
This is a tracking issue for packaging databroker handlers. All of the handlers that were formerly developer in the databroker source tree have been moved to bluesky/area-detector-handlers. There are a couple other handlers in the wild, living mostly in `profile_collection` repos, that need to be captured in a proper repository, that is:

(1) in some installable package, not in `profile_collection` repos
(2) using the new `'databroker.handlers'` entrypoint so it is discoverable via `databroker.core.discover_handlers()`.

This issue is not a blocking for releasing 1.0, but it is a blocking for _deploying_ 1.0 at beamlines that rely on these yet-unpackaged handlers.

## Known handlers
- [ ] Custom handlers for XPRESS3 and Zebra at SRX https://github.com/NSLS-II-SRX/profile_collection/search?q=register_handler&unscoped_q=register_handler
- [ ]  Pizza box at ISS https://github.com/NSLS-II-ISS/profile_collection/blob/4dc1661df09b3dffc1466031456300ddfc3c2692/startup/10-detectors.py#L754-L840
- [ ] Pizza box at QAS https://github.com/NSLS-II-QAS/profile_collection/blob/master/startup/11-handlers.py
- [ ] Handlers at SIX
- [ ] https://github.com/NSLS-II-HXN/hxntools/blob/master/hxntools/handlers/timepix.py
- [ ] IOS specs handler

**Comment by awalter-bnl** [comment]
Friendly reminder, There is also a handler at IOS for their specs detector that should be included.

**Comment by danielballan** [comment]
Thanks. Meant to go back and find your Slack message to verify that I transcribed it right (from memory). Edited original post.

**Comment by MikeHart85** [comment]
List of all the handlers I've been able to find, which are defined or referenced among the beamline profiles (searching for `HandlerBase` and `register_handler` in all profiles):

### In [eiger-io](https://github.com/NSLS-II/eiger-io)
- [EigerHandler](https://github.com/NSLS-II/eiger-io/blob/726ce0be4e085fad5bc584e098304fbc66da119a/eiger_io/fs_handler.py#L83-L201)
- [EigenHandlerDask](https://github.com/NSLS-II/eiger-io/blob/726ce0be4e085fad5bc584e098304fbc66da119a/eiger_io/fs_handler_dask.py#L140-L193)
- Used by CHX in [92-handler2.py](https://github.com/NSLS-II-CHX/profile_collection/blob/master/startup/92-handler2.py#L100-L108)
- [Commented out CHX line](https://github.com/NSLS-II-CHX/profile_collection/blob/master/startup/90-settings.py#L28-L29) references `LazyEigerHandler`, but this seems to not exist anymore
- Used by ISR in [20-area-detectors.py](https://github.com/NSLS-II-CHX/profile_collection/blob/master/startup/20-area-detectors.py#L143)

### In [ISS profile](https://github.com/NSLS-II-ISS/profile_collection)
- [PizzaBox Handlers](https://github.com/NSLS-II-ISS/profile_collection/blob/master/startup/10-detectors.py#L753-L839)
- [HDF5DFHandler](https://github.com/NSLS-II-ISS/profile_collection/blob/master/startup/50-insert_analysis.py#L73-85) (only used in [test](https://github.com/NSLS-II-ISS/profile_collection/blob/master/tests/test_analysis_write.py#L60)?)
- [HDF5DFWriter](https://github.com/NSLS-II-ISS/profile_collection/blob/master/startup/50-insert_analysis.py#L87-108) (never registered? not sure it's used at all)
- [SpectroscopyInterpHandler](https://github.com/NSLS-II-ISS/profile_collection/blob/master/startup/50-insert_analysis.py#L293) (never referenced again)
- [ElectrometerBinFileHandler](https://github.com/NSLS-II-ISS/profile_collection/blob/master/startup/30-electrometer.py#L155-227)

### In [TES Profile](https://github.com/NSLS-II-TES/profile_collection/blob/master/startup/)
- [BulkXSPRESS](https://github.com/NSLS-II-ISS/profile_collection/blob/master/startup/27-xspress3.py#L42-52)

### In [QAS Profile](https://github.com/NSLS-II-QAS/profile_collection/blob/master/startup/)
- [PizzaBox Handlers](https://github.com/NSLS-II-QAS/profile_collection/blob/master/startup/11-handlers.py#L11-142)
- [PizzaBoxAnHandlerTxt](https://github.com/NSLS-II-QAS/profile_collection/blob/master/startup/test_new_handler.py#L15-43) (tests only?)

### In [SRX Profile](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/)
- [ZebraHDF5Handler](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/91-flyscans.py#L474)
- [SISHDF5Handler](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/91-flyscans.py#L482)
- [BulkDexela](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/22-dexela.py#L41)
- [BulkXSPRESS](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/80-areadetectors.py#L174)
- [BulkMerlinDEBUG](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/80-areadetectors.py#L189)
- [BulkMerlin](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/80-areadetectors.py#L183)

### In [SIX Profile](https://github.com/NSLS-II-SIX/profile_collection/blob/master/startup/)
- [HDF5SingleHandler](https://github.com/NSLS-II-SIX/profile_collection/blob/master/startup/22-rixscam.py#L19) (only inherited by AD Handler below)
- [AreaDetectorHDF5SingleHandler](https://github.com/NSLS-II-SIX/profile_collection/blob/master/startup/22-rixscam.py#L66) (only `register_handler` [commented out](https://github.com/NSLS-II-SIX/profile_collection/blob/master/startup/22-rixscam.py#L87)?)
- Above also repeated in [startup/November 2018 22-rixscam.pyno](https://github.com/NSLS-II-SIX/profile_collection/blob/master/startup/November%202018%2022-rixscam.pyno)

### In [LIX Profile](https://github.com/NSLS-II-LIX/profile_collection/blob/master/startup/)
- [PilatusCBFHandler](https://github.com/NSLS-II-LIX/profile_collection/blob/master/startup/33-CBFhandler.py#L36-L113)

### In [IOS Profile](https://github.com/NSLS-II-IOS/profile_collection/blob/master/startup/)
- [Specs_HDF5SingleHandler_DataFrame](https://github.com/NSLS-II-IOS/profile_collection/blob/master/startup/02-handler.py#L7-L68)

Could not find the `hxntools` handlers referenced directly in any profiles, but the [_handler_name / spec](https://github.com/NSLS-II-HXN/hxntools/blob/master/hxntools/handlers/timepix.py#L68-L69) `TPX_HDF5` is referenced in the SRX profile [here](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/22-dexela.py#L57), [here](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/80-areadetectors.py#L506) and [here](https://github.com/NSLS-II-SRX/profile_collection/blob/master/startup/80-areadetectors.py#L539)... I assume that connects somehow? There may be more handlers that connect that way, that I haven't found yet.

**Comment by MikeHart85** [comment]
@danielballan: How should these be packaged? All in one big package? By beamline (there seems to be some overlap/copy-pasting)? Each in separate packages? 

What about the `eiger-io` ones? They are already a package, but it doesn't look entrypoint enabled... should it just be updated, or repackaged with the others?

**Comment by danielballan** [comment]
I believe that everything still relevant from `eiger-io` was merged into `area-detector-handlers` in https://github.com/bluesky/area-detector-handlers/pull/5

I would like to avoid beamline-specific packages because I think these will tend to become multi-beamline and multi-facility, even if some of them happen to be in use at one beamline today.

Everything that originates from an Area Detector (by which I mean [the Area Detector IOC](https://github.com/areaDetector) not "area detectors" in general sense) can go in `area-detector-handlers`. I believe that includes Dexela, XPRESS, Pilatus. It _may_ include Merlin, but I'm not sure if that actually uses Area Detector; maybe @tacaswell or @mrakitin can fill in the gaps in my knowledge here.It sounds like we need a `pizzabox-handlers` package and a `zerbabox-handlers` package. Not sure where the rest of the ISS ones fit and how likely those formats are to generalize. In the short term we could go with an `iss-handlers package with the plan to split it up and/or rebrand in the future, just to keep things moving.

**Comment by mrakitin** [comment]
Dexela uses Mark Rivers' AreaDetector, should go there as well.

Agree about the pizzabox and zebrabox handlers.

**Comment by stuartcampbell** [comment]
Would it make sense to have an `nsls2-detector-handlers` package as a staging place for handlers that are specific to us at the moment?  Or is this too much like a 'beamline package' @danielballan ?

**Comment by danielballan** [comment]
I like `nsls2-detector-handlers` as a staging place.

**Comment by MikeHart85** [comment]
General update on issues encountered:

1. ISS and QAS both have multiple PizzaBox handlers with the same name and spec, but different implementations. Not sure how to reconcile this without changing spec names or making beamline-specific repos.
2. PilatusCBFHandler at LIX appears to operate on local and gpfs mounted files, with configurable path which is referenced in other parts of the profile as well. I'm not sure
3. `AD_EIGER_SLICE` is a spec that is referenced in profiles but isn't currently provided by `area-detector-handlers`. This should be just a matter of adding an entrypoint associating it with EigerHandler, but need to test that it works as expected.
